src/Controller/BaseController.php
<?php

namespace App\Controller;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

abstract class BaseController extends AbstractController
{
    protected function getUser(): User
    {
        return parent::getUser();
    }
}

templates/base.html.twig
<!doctype html>
<html lang="en">

<head>
    <title>{% block title %}Welcome to the SpaceBar{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block stylesheets %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('css/font-awesome.css') }}">
        <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
    {% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark navbar-bg mb-5">
    <a style="margin-left: 75px;" class="navbar-brand space-brand" href="{{ path('app_homepage') }}">Sanimal</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a style="color: #fff;" class="nav-link" href="#">Local Asteroids</a>
            </li>
            <li class="nav-item">
                <a style="color: #fff;" class="nav-link" href="#">Weather</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if is_granted('ROLE_USER') %}
                <li class="nav-item dropdown" style="margin-right: 75px;">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img class="nav-profile-img rounded-circle" src="{{ app.user.avatarUrl(100) }}">
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{{ path('app_account') }}">Profile</a>
                        {% if is_granted('ROLE_ADMIN_ESTABLECIMIENTO') %}
                            <a class="dropdown-item" href="{{ path('admin_list_establecimiento') }}">Establecimientos</a>
                        {% endif %}
                        <a class="dropdown-item" href="{{ path('app_logout') }}">Logout</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a style="color: #fff;" class="nav-link" href="{{ path('app_login') }}">Login</a>
                </li>
                <li class="nav-item">
                    <a style="color: #fff;" class="nav-link" href="{{ path('app_register') }}">Registrar</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

{% block body %}{% endblock %}

<footer class="footer">
    <div class="container text-center">
        <span class="text-muted">Hecho con <i class="fa fa-heart" style="color: red;"></i> Sectorial MPCyT <a href="https://santafe.gov.ar">Gobierno Santa Fe</a></span>
    </div>
</footer>


{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script>
        $('.dropdown-toggle').dropdown();
    </script>
{% endblock %}
</body>
</html>

templates/establecimiento_base.html.twig
{% extends 'base.html.twig'%}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="p-3 mt-4">
                    {% block content_body %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}